apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: cirq-triage-party
deploy:
  kubectl:
    manifests:
    - dev_tools/triage-party/kubernetes/01_ns/namespace.yaml
    - dev_tools/triage-party/kubernetes/02_deployment/configmap.yaml
    - dev_tools/triage-party/kubernetes/02_deployment/deployment.yaml
    - dev_tools/triage-party/kubernetes/03_svc/service.yaml
